spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL} # jdbc:postgresql://localhost:5432/customer_service
    username: ${DB_USERNAME} # postgres
    password: ${DB_PASSWORD} # 12345
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: ${KAFKA_LOCATION} # localhost:9092
    group-id: consumer-group
    topic:
      name: test-topic
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME} # bardayilmaz35@gmail.com
    password: ${EMAIL_PASSWORD} # ywjkdfvmnsonztxn
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: false

mail:
  host: http://localhost:3000

app:
  jwtSecret: ${JWT_SECRET} #someStrongSecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

server:
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

kafka:
  fish-box-topic: ${FISH_BOX_TOPIC}
  customer-topic: ${CUSTOMER_TOPIC}
  auction-topic: ${AUCTION_TOPIC}

